ALTER TABLE videos ADD COLUMN IF NOT EXISTS fraud_detected BOOLEAN DEFAULT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS fraud_messages TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS fraud_analyzed_at TIMESTAMP;
